import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def plot_resilience_trend(csv_path: str,
                          output_folder: str = "data/processed/plots",
                          province_label: str = "Ontario") -> str:
    """
    Generates automated visualizations for the Labour Stability Index (LSI)
    and Resilience Score using Matplotlib and Seaborn.

    Produces:
        1. Line chart of Resilience Score over time.
        2. Optional multi-age-group comparison plot.

    Parameters
    ----------
    csv_path : str
        Path to the processed CSV generated by the ETL pipeline.
    output_folder : str
        Directory where plots will be saved.
    province_label : str
        Label for chart titles.

    Returns
    -------
    str
        Path to the saved plot file.
    """

    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Processed CSV not found: {csv_path}")

    os.makedirs(output_folder, exist_ok=True)

    df = pd.read_csv(csv_path)

    # Ensure numeric types
    df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
    df["Resilience_Score"] = pd.to_numeric(df["Resilience_Score"], errors="coerce")

    # Use Seaborn theme
    sns.set_theme(style="whitegrid", context="talk")

    # -----------------------------
    # 1. Single Trend Line Plot
    # -----------------------------
    plt.figure(figsize=(14, 7))
    sns.lineplot(
        data=df,
        x="Year",
        y="Resilience_Score",
        estimator="mean",
        ci=None,
        color="#1f77b4",
        linewidth=2.5,
        label="Resilience Score"
    )

    # Add smoothed trend line
    sns.regplot(
        data=df,
        x="Year",
        y="Resilience_Score",
        scatter=False,
        lowess=True,
        color="red",
        label="Smoothed Trend",
        line_kws={"linewidth": 2, "alpha": 0.7}
    )

    plt.title(f"{province_label} Labour Market Resilience (1976–2025)")
    plt.xlabel("Year")
    plt.ylabel("Resilience Score (0–100)")
    plt.legend()
    plt.tight_layout()

    output_path = os.path.join(output_folder, "resilience_trend.png")
    plt.savefig(output_path, dpi=300)
    plt.close()

    # -----------------------------
    # 2. Multi Age-Group Comparison
    # -----------------------------
    plt.figure(figsize=(14, 7))
    sns.lineplot(
        data=df,
        x="Year",
        y="Resilience_Score",
        hue="AgeGroup",
        palette="tab10",
        linewidth=2
    )

    plt.title(f"{province_label} Resilience Score by Age Group")
    plt.xlabel("Year")
    plt.ylabel("Resilience Score (0–100)")
    plt.legend(title="Age Group")
    plt.tight_layout()

    output_path_age = os.path.join(output_folder, "resilience_by_age_group.png")
    plt.savefig(output_path_age, dpi=300)
    plt.close()

    print(f"[SUCCESS] Plots saved to: {output_folder}")
    return output_folder
